const MonthData = [
    {
        name:"January",
        shortName:"Jan",
        daysInMonth:31,
    },
    {
        name:"February",
        shortName:"Feb",
        daysInMonth:28,
    },
    {
        name:"March",
        shortName:"Mar",
        daysInMonth:31,
    },
    {
        name:"April",
        shortName:"Apr",
        daysInMonth:30,
    },
    {
        name:"May",
        shortName:"May",
        daysInMonth:31,
    },
    {
        name:"June",
        shortName:"Jun",
        daysInMonth:30,
    },
    {
        name:"July",
        shortName:"Jul",
        daysInMonth:31,
    },
    {
        name:"August",
        shortName:"Aug",
        daysInMonth:31,
    },
    {
        name:"September",
        shortName:"Spt",
        daysInMonth:30,
    },
    {
        name:"Octobor",
        shortName:"Oct",
        daysInMonth:31,
    },
    {
        name:"November",
        shortName:"Nov",
        daysInMonth:30,
    },
    {
        name:"December",
        shortName:"Dec",
        daysInMonth:31,
    },
]
export default MonthData;