const MonthData = [
    {
        name:"January",
        shortName:"Jan",
        daysInMonth:31,
    },
    {
        name:"January",
        shortName:"Jan",
        daysInMonth:31,
    },
    {
        name:"January",
        shortName:"Jan",
        daysInMonth:31,
    },
    {
        name:"January",
        shortName:"Jan",
        daysInMonth:31,
    },
    {
        name:"January",
        shortName:"Jan",
        daysInMonth:31,
    },
    {
        name:"January",
        shortName:"Jan",
        daysInMonth:31,
    },
    {
        name:"January",
        shortName:"Jan",
        daysInMonth:31,
    },
    {
        name:"January",
        shortName:"Jan",
        daysInMonth:31,
    },
    {
        name:"January",
        shortName:"Jan",
        daysInMonth:31,
    },
    {
        name:"January",
        shortName:"Jan",
        daysInMonth:31,
    },
    {
        name:"January",
        shortName:"Jan",
        daysInMonth:31,
    },
    {
        name:"January",
        shortName:"Jan",
        daysInMonth:31,
    },
]
export default MonthData;